CREATE TABLE [dbo].[M_Request] (
    [Request_Id]             BIGINT           IDENTITY (1, 1) NOT NULL,
    [IP]                     NVARCHAR (50)    NULL,
    [Name]                   NVARCHAR (50)    NULL,
    [NetMask]                NVARCHAR (50)    NULL,
    [Description]            NVARCHAR (500)   NULL,
    [WinChange_DeviceID]     NVARCHAR (50)    NULL,
    [WinChange_DeviceName]   NVARCHAR (50)    NULL,
    [NCM_Host_Id]            INT              NULL,
    [NCM_Group_Id]           INT              NULL,
    [NCM_Object_SubType]     NVARCHAR (50)    NULL,
    [NCM_SNMP_Version_Id]    INT              NULL,
    [NCM_Community]          NVARCHAR (50)    NULL,
    [CiscoACS_Host_Id]       INT              NULL,
    [CiscoACS_Device_Id]     INT              NULL,
    [CiscoACS_Location]      NVARCHAR (50)    NULL,
    [CiscoACS_DeviceType]    NVARCHAR (50)    NULL,
    [CiscoACS_SharedSecret]  NVARCHAR (150)   NULL,
    [CiscoACS_LegacyTACACS]  BIT              NULL,
    [CiscoACS_SingleConnect] BIT              NULL,
    [PRTG_Host_Id]           INT              NULL,
    [PRTG_Group_Id]          INT              NULL,
    [PRTG_Device_Id]         INT              NULL,
    [Hostmonitor_Port]       NVARCHAR (50)    NULL,
    [Request_Type_Id]        INT              NOT NULL,
    [Source_Id]              INT              NULL,
    [Request_Guid]           UNIQUEIDENTIFIER NULL,
    [CreatedBy]              NVARCHAR (100)   NULL,
    [CreatedUTCDate]         DATETIME         NULL,
    [LastModifiedBy]         NVARCHAR (100)   NULL,
    [LastModifiedUTCDate]    DATETIME         NULL,
    [IsActive]               BIT              NOT NULL,
    CONSTRAINT [PK_M_Request] PRIMARY KEY CLUSTERED ([Request_Id] ASC),
    CONSTRAINT [FK_M_Request_Lk_Request_Type] FOREIGN KEY ([Request_Type_Id]) REFERENCES [dbo].[Lk_Request_Type] ([Request_Type_Id]),
    CONSTRAINT [FK_M_Request_Lk_Source] FOREIGN KEY ([Source_Id]) REFERENCES [dbo].[Lk_Source] ([Source_Id])
);

